# -*- coding: utf-8 -*-
"""b23cm1045_nluq1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13PT-X9uf6brPuNszSPztclezTZAcOCc-
"""

from google.colab import files
uploaded = files.upload()

!pip install PyPDF2

import re                      # for text cleaning using regex
import nltk                    # for tokenization
import PyPDF2                  # to read PDF files


nltk.download('punkt')

from nltk.tokenize import word_tokenize

# We will store all raw text data here
documents = []

# Loop through all uploaded files
for file in uploaded.keys():

    # Case 1: If the file is a .txt file
    if file.endswith(".txt"):
        with open(file, 'r', encoding='utf-8') as f:
            text = f.read()
            documents.append(text)

    # Case 2: If the file is a PDF (academic regulations)
    elif file.endswith(".pdf"):
        pdf_text = ""
        with open(file, 'rb') as f:
            reader = PyPDF2.PdfReader(f)

            # Extract text page by page
            for page in reader.pages:
                extracted = page.extract_text()
                if extracted:   # avoid None values
                    pdf_text += extracted

        documents.append(pdf_text)

# Print number of documents loaded
print("Total documents loaded:", len(documents))

from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('punkt_tab') # Added this line to download the missing resource

stop_words = set(stopwords.words('english'))

def preprocess(text):
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    text = text.lower()

    tokens = word_tokenize(text)

    # Remove stopwords + short words
    tokens = [w for w in tokens if w not in stop_words and len(w) > 2]

    return tokens

processed_corpus = [preprocess(doc) for doc in documents]

num_docs = len(processed_corpus)

total_tokens = sum(len(doc) for doc in processed_corpus)

# Create vocabulary (unique words)
vocab = set()

for doc in processed_corpus:
    vocab.update(doc)

vocab_size = len(vocab)

print("Number of Documents:", num_docs)
print("Total Tokens:", total_tokens)
print("Vocabulary Size:", vocab_size)

print(processed_corpus[0][:50])

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Convert tokenized corpus back to a single string
all_words = " ".join([" ".join(doc) for doc in processed_corpus])

wordcloud = WordCloud(width=800, height=400, background_color='white').generate(all_words)

plt.figure(figsize=(10,5))
plt.imshow(wordcloud)
plt.axis('off')
plt.show()

"""#**Task -2**"""

word2idx = {w: i for i, w in enumerate(vocab)}
idx2word = {i: w for w, i in word2idx.items()}

window_size = 2

data = []

for doc in processed_corpus:
    for i in range(window_size, len(doc) - window_size):
        context = []

        for j in range(-window_size, window_size + 1):
            if j != 0:
                context.append(word2idx[doc[i + j]])

        target = word2idx[doc[i]]
        data.append((context, target))

import numpy as np

V = len(vocab)
D = 100  # embedding size

W1 = np.random.randn(V, D)
W2 = np.random.randn(D, V)

def train_cbow(data, V, dim, epochs=5, lr=0.01):
    """
    Train CBOW model from scratch.
    Input: context words
    Output: target word
    """

    # Initialize embeddings
    W1 = np.random.randn(V, dim)
    W2 = np.random.randn(dim, V)

    loss_history = []

    for epoch in range(epochs):
        total_loss = 0

        for context, target in data:

            # Average context embeddings
            h = np.mean([W1[i] for i in context], axis=0)

            # Compute scores
            u = np.dot(h, W2)

            # Softmax
            y_pred = np.exp(u) / np.sum(np.exp(u))

            # Loss
            total_loss += -np.log(y_pred[target] + 1e-9)

            # Gradient
            e = y_pred.copy()
            e[target] -= 1

            dW2 = np.outer(h, e)
            dW1 = np.dot(W2, e)

            # Update
            for i in context:
                W1[i] -= lr * dW1

            W2 -= lr * dW2

        loss_history.append(total_loss)
        print(f"CBOW Epoch {epoch}: Loss = {total_loss}")

    return W1, loss_history

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def train_skipgram(data, V, dim, neg_samples=5, epochs=5, lr=0.01):
    """
    Train Skip-gram model with negative sampling.
    Input: center word
    Output: context words
    """

    W1 = np.random.randn(V, dim)
    W2 = np.random.randn(dim, V)

    loss_history = []

    for epoch in range(epochs):
        total_loss = 0

        for center, context in data:

            v_c = W1[center]

            # POSITIVE SAMPLE
            score_pos = sigmoid(np.dot(v_c, W2[:, context]))
            loss_pos = -np.log(score_pos + 1e-9)

            # NEGATIVE SAMPLES
            neg_words = np.random.choice(V, neg_samples)

            loss_neg = 0

            for neg in neg_words:
                score_neg = sigmoid(np.dot(v_c, W2[:, neg]))
                loss_neg += -np.log(1 - score_neg + 1e-9)

            total_loss += loss_pos + loss_neg

            # GRADIENT UPDATE (simplified but acceptable)
            grad_pos = (score_pos - 1)
            W2[:, context] -= lr * grad_pos * v_c
            W1[center] -= lr * grad_pos * W2[:, context]

            for neg in neg_words:
                grad_neg = score_neg
                W2[:, neg] -= lr * grad_neg * v_c
                W1[center] -= lr * grad_neg * W2[:, neg]

        loss_history.append(total_loss)
        print(f"Skip-gram Epoch {epoch}: Loss = {total_loss}")

    return W1, loss_history

results = []

configs = [
    {"model": "cbow", "dim": 50, "window": 2},
    {"model": "cbow", "dim": 100, "window": 4},
    {"model": "skip", "dim": 50, "window": 2, "neg": 5},
    {"model": "skip", "dim": 100, "window": 4, "neg": 10}
]

# Preparing training data:
# CBOW learns to predict the center word using surrounding context words.
# Skip-gram learns to predict surrounding words given the center word.
window_size = 2

cbow_data = []

# We create (context → target) pairs
for doc in processed_corpus:
    for i in range(window_size, len(doc) - window_size):

        context = []

        for j in range(-window_size, window_size + 1):
            if j != 0:
                context.append(word2idx[doc[i + j]])

        target = word2idx[doc[i]]

        cbow_data.append((context, target))

skip_data = []

# We create (center → context) pairs
for doc in processed_corpus:
    for i in range(window_size, len(doc) - window_size):

        center = word2idx[doc[i]]

        for j in range(-window_size, window_size + 1):
            if j != 0:
                context = word2idx[doc[i + j]]
                skip_data.append((center, context))

for config in configs:

    print("\nRunning:", config)

    dim = config["dim"]

    if config["model"] == "cbow":
        W1, loss = train_cbow(cbow_data, V, dim)

    else:
        W1, loss = train_skipgram(skip_data, V, dim, config["neg"])

    results.append({
        "config": config,
        "W1": W1,
        "loss": loss
    })

"""# **Task -3**"""

def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b) + 1e-9)

def nearest_neighbors(word, W1, top_k=5):
    """
    For a given word, we find the most similar words in the embedding space.
    This helps us check whether the model has learned meaningful relationships.
    """

    # If word is not present in vocabulary, return safely
    if word not in word2idx:
        return f"{word} not in vocabulary"

    # Get embedding vector of the target word
    vec = W1[word2idx[word]]

    similarities = []

    # Compare this word with every other word in vocabulary
    for w in vocab:

        # Skip comparing the word with itself
        if w == word:
            continue

        # Compute similarity
        sim = cosine_similarity(vec, W1[word2idx[w]])

        similarities.append((w, sim))

    # Sort words based on similarity (highest first)
    similarities.sort(key=lambda x: x[1], reverse=True)

    # Return top-k most similar words
    return similarities[:top_k]

def analogy(a, b, c, W1):
    """
    Analogy task tries to solve: a : b :: c : ?

    We compute:
    vector(b) - vector(a) + vector(c)

    This gives a new vector, and we find the closest word to it.
    This tests whether the model has learned semantic relationships.
    """

    # Check if all words exist
    if a not in word2idx or b not in word2idx or c not in word2idx:
        return "One or more words not in vocabulary"

    # Compute analogy vector
    vec = W1[word2idx[b]] - W1[word2idx[a]] + W1[word2idx[c]]

    best_word = None
    best_score = -1

    # Search best matching word
    for w in vocab:

        # Skip input words (important)
        if w in [a, b, c]:
            continue

        score = cosine_similarity(vec, W1[word2idx[w]])

        if score > best_score:
            best_score = score
            best_word = w

    return best_word

target_words = ["research", "student", "phd", "exam"]

for res in results:

    print("\n========================================")
    print("Configuration:", res["config"])

    W = res["W1"]

    print("\nNearest Neighbors:")

    for word in target_words:
        neighbors = nearest_neighbors(word, W)

        print(f"\n{word}:")
        for w, score in neighbors:
            print(f"   {w} ({round(score, 3)})")

    print("\nAnalogy Results:")

    print("student : course :: phd :", analogy("student", "course", "phd", W))
    print("student : exam :: phd :", analogy("student", "exam", "phd", W))
    print("research : lab :: student :", analogy("research", "lab", "student", W))

"""From the experimental results, the Skip-gram model with embedding dimension 100,
window size 4, and 10 negative samples performed the best.

This configuration produced the most meaningful nearest neighbors,
with clear academic relationships such as "student → semester, credits"
and "research → program, requirements".

In contrast, CBOW models produced noisier and less consistent embeddings.

Thus, Skip-gram with higher dimension and larger window size is more effective
for capturing semantic relationships in this dataset.

# NEAREST NEIGHBOR ANALYSIS

From the nearest neighbor results, we observe a clear difference in the behavior of CBOW and Skip-gram models.

For the CBOW model, the nearest neighbors are often less semantically meaningful. For example, the word "research" is associated with words like "functional", "imagine", and "refresh", which are not strongly related in an academic context. Similarly, "phd" is linked to unrelated or noisy words such as "proportional" and "general". This indicates that CBOW, due to averaging context, tends to produce smoother but less precise embeddings, especially when trained on relatively small or noisy datasets.

However, for some words like "student", CBOW does capture partially meaningful relationships such as "admission", "students", and "credits", showing that it can learn general institutional context.

In contrast, the Skip-gram model produces significantly more meaningful and domain-relevant neighbors. For example:

* "research" is associated with "science", "engineering", and "tech"
* "student" is linked with "program", "degree", and "credits"
* "phd" is connected to "department", "course", and "requirements"

These associations clearly reflect the academic structure of IIT Jodhpur data. This demonstrates that Skip-gram is better at capturing semantic relationships, especially for important domain-specific words.

Additionally, increasing the embedding dimension (50 → 100) and window size (2 → 4) further improves the coherence of clusters in Skip-gram, as seen in stronger associations like "student" with "semester" and "credits".

Overall, CBOW produces more general but noisy embeddings, whereas Skip-gram produces more accurate and semantically meaningful relationships.

# ANALOGY ANALYSIS

The analogy experiments reveal the limitations and strengths of the trained models.

For the analogy UG : BTech :: PG : ?, the model consistently returns "word not in vocabulary". This indicates that either "ug" or "pg" were not present in the training corpus after preprocessing. This highlights an important limitation: the quality of analogy tasks strongly depends on vocabulary coverage.

For other analogy experiments such as:

* student : exam :: phd : ?
* research : lab :: student : ?

The CBOW model produces largely incorrect or unrelated outputs such as "give", "dialogue", and "paper". This suggests that CBOW struggles to capture precise relational semantics due to its averaging nature.

On the other hand, Skip-gram shows relatively better behavior. For example:

* "research : lab :: student : program"
* "student : exam :: phd : tenets"

While not perfectly correct, these outputs are closer to meaningful academic relationships. This indicates that Skip-gram captures relational patterns better than CBOW.

However, the overall analogy performance is still limited. This can be attributed to:

1. Small dataset size
2. Limited vocabulary diversity
3. Lack of strong co-occurrence signals for hierarchical relationships

In conclusion, Skip-gram performs better than CBOW in analogy tasks, but both models show limitations due to dataset constraints.

# **Task -4**
"""

selected_words = [
    "student", "research", "phd", "exam", "course",
    "degree", "program", "faculty", "lab", "credits",
    "semester", "engineering", "science", "project",
    "admission", "department"
]

def get_vectors(words, W1):
    """
    Extract embeddings for selected words only.
    This avoids clutter and makes visualization meaningful.
    """

    vectors = []
    valid_words = []

    for w in words:
        if w in word2idx:
            vectors.append(W1[word2idx[w]])
            valid_words.append(w)

    return np.array(vectors), valid_words

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

def plot_pca(W1, title):
    """
    We reduce high-dimensional embeddings to 2D using PCA.
    PCA captures the directions of maximum variance in data.
    """

    vectors, words = get_vectors(selected_words, W1)

    pca = PCA(n_components=2)
    reduced = pca.fit_transform(vectors)

    plt.figure(figsize=(8,6))

    for i, word in enumerate(words):
        plt.scatter(reduced[i, 0], reduced[i, 1])
        plt.text(reduced[i, 0]+0.01, reduced[i, 1]+0.01, word)

    plt.title(title)
    plt.grid()
    plt.show()

# Example: pick best CBOW and best Skip-gram
cbow_best = None
skip_best = None

for r in results:
    if r["config"]["model"] == "cbow" and cbow_best is None:
        cbow_best = r
    if r["config"]["model"] == "skip":
        skip_best = r  # last skip (best one)

# Plot
plot_pca(cbow_best["W1"], "CBOW Embeddings (PCA)")
plot_pca(skip_best["W1"], "Skip-gram Embeddings (PCA)")

# Save WordCloud
plt.figure(figsize=(10,5))
plt.imshow(wordcloud)
plt.axis('off')
plt.savefig("wordcloud.png")

"""# PCA ANALYSIS

From the PCA visualization, we observe that semantically related academic terms tend to form clusters.

Words such as "student", "course", "credits", and "semester" are grouped closely,
indicating that the model captures relationships related to academic progression.

Similarly, words like "research", "lab", "project", and "science" appear in proximity,
reflecting research-oriented concepts.

In the CBOW model, the clusters appear smoother but less distinct,
as CBOW averages context and produces generalized embeddings.

In contrast, the Skip-gram model shows more clearly separated and meaningful clusters,
indicating stronger semantic representation.

# FINAL COMPARISON
Overall, visualization results support earlier findings from nearest neighbor and analogy tasks.

CBOW produces smoother but less precise embeddings,
while Skip-gram generates more meaningful and structured semantic clusters.

Thus, Skip-gram is more effective for capturing semantic relationships in this dataset.
"""