# -*- coding: utf-8 -*-
"""b23cm1045_nluq2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n_CNM5l0ZC9VtdRkOAflo3PFHpDqh_ii
"""

from google.colab import files
uploaded = files.upload()

# Read names from file
with open("TrainingNames.txt", "r") as f:
    names = f.read().splitlines()

print(names[:10])

chars = sorted(list(set("".join(names))))

# Create mapping from character to index
char_to_idx = {ch: i for i, ch in enumerate(chars)}
# Reverse mapping (index to character)
idx_to_char = {i: ch for ch, i in char_to_idx.items()}

vocab_size = len(chars)

print("Unique characters:", chars)
print("Vocabulary size:", vocab_size)

# Encode names into integer sequences
encoded_names = []

for name in names:
    encoded = [char_to_idx[ch] for ch in name]
    encoded_names.append(encoded)

import torch
import torch.nn as nn


class CharRNN(nn.Module):

    def __init__(self, vocab_size, hidden_size):
        super(CharRNN, self).__init__()

        # Store hidden size for later use
        self.hidden_size = hidden_size

        # Embedding layer converts character indices into dense vectors
        self.embedding = nn.Embedding(vocab_size, hidden_size)

        # Basic RNN layer
        self.rnn = nn.RNN(hidden_size, hidden_size, batch_first=True)

        # Fully connected layer to predict next character
        self.fc = nn.Linear(hidden_size, vocab_size)

    def forward(self, x, hidden):
        # Convert indices → embeddings
        x = self.embedding(x)
        out, hidden = self.rnn(x, hidden)

        # Convert hidden states → output predictions
        out = self.fc(out)

        return out, hidden

    def init_hidden(self, batch_size):
        # Initialize hidden state with zeros
        return torch.zeros(1, batch_size, self.hidden_size)

hidden_size = 128

model = CharRNN(vocab_size, hidden_size)

# Loss function (used for classification)
criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=0.003)

epochs = 5
for epoch in range(epochs):
    total_loss = 0

    for name in encoded_names:
        # Input = all chars except last
        # Target = all chars except first
        input_seq = torch.tensor(name[:-1]).unsqueeze(0)
        target_seq = torch.tensor(name[1:]).unsqueeze(0)

        # Initialize hidden state
        hidden = model.init_hidden(1)

        # Reset gradients
        optimizer.zero_grad()

        # Forward pass
        output, hidden = model(input_seq, hidden)

        # Compute loss
        loss = criterion(output.squeeze(), target_seq.squeeze())

        # Backpropagation
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

import random

# Function to generate a name from trained model
def generate_name(model, start_char, length=10):

    model.eval()

    # Start with given character
    input_char = torch.tensor([[char_to_idx[start_char]]])
    hidden = model.init_hidden(1)

    name = start_char

    for _ in range(length):
        output, hidden = model(input_char, hidden)

        # Convert output to probabilities
        probs = torch.softmax(output[0, -1], dim=0).detach().numpy()

        # Randomly pick next character
        idx = random.choices(range(vocab_size), weights=probs)[0]

        char = idx_to_char[idx]
        name += char

        input_char = torch.tensor([[idx]])

    return name


# Generate some names
for _ in range(5):
    print(generate_name(model, random.choice(chars)))

"""# **BLSTM**"""

import torch
import torch.nn as nn

class CharBLSTM(nn.Module):

    def __init__(self, vocab_size, hidden_size):
        super(CharBLSTM, self).__init__()

        self.hidden_size = hidden_size

        # Each character → dense vector
        self.embedding = nn.Embedding(vocab_size, hidden_size)

        # Bidirectional LSTM (forward + backward)
        self.lstm = nn.LSTM(
            input_size=hidden_size,
            hidden_size=hidden_size,
            batch_first=True,
            bidirectional=True
        )

        # Since bidirectional → output size = 2 * hidden_size
        self.fc = nn.Linear(hidden_size * 2, vocab_size)

    def forward(self, x, hidden):

        # Convert indices → embeddings
        x = self.embedding(x)

        # Pass through BLSTM
        out, hidden = self.lstm(x, hidden)

        # Predict next character
        out = self.fc(out)

        return out, hidden

    def init_hidden(self, batch_size):
        # Initialize hidden + cell states (2 directions)
        return (
            torch.zeros(2, batch_size, self.hidden_size),
            torch.zeros(2, batch_size, self.hidden_size)
        )

hidden_size = 128
blstm_model = CharBLSTM(vocab_size, hidden_size)

criterion = nn.CrossEntropyLoss()

# Lower LR → more stable for BLSTM
optimizer = torch.optim.Adam(blstm_model.parameters(), lr=0.001)

# Train longer → BLSTM needs more time
epochs = 15

for epoch in range(epochs):
    total_loss = 0

    for name in encoded_names:

        input_seq = torch.tensor(name[:-1]).unsqueeze(0)
        target_seq = torch.tensor(name[1:]).unsqueeze(0)

        hidden = blstm_model.init_hidden(1)

        optimizer.zero_grad()

        output, hidden = blstm_model(input_seq, hidden)

        loss = criterion(output.squeeze(), target_seq.squeeze())

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

import torch
import random

def generate_name_blstm(model, start_char="A", max_len=15, temperature=0.7):

    model.eval()

    name = start_char
    current_char = start_char

    for _ in range(max_len):

        # Reinitialize hidden state each step (important for BLSTM)
        hidden = model.init_hidden(1)

        input_char = torch.tensor([[char_to_idx[current_char]]])

        output, hidden = model(input_char, hidden)

        logits = output[0, -1] / temperature
        probs = torch.softmax(logits, dim=0)

        #  Repetition penalty
        for ch in set(name[-3:]):  # last 3 chars
            if ch in char_to_idx:
                probs[char_to_idx[ch]] *= 0.5

        probs = probs / probs.sum()  # normalize

        idx = torch.multinomial(probs, 1).item()
        char = idx_to_char[idx]

        # Stop if newline OR name is already reasonable length
        if char == '\n' or len(name) > 6:
            break

        name += char
        current_char = char

    return name

for _ in range(5):
    start = random.choice(chars)
    print(generate_name_blstm(blstm_model, start))

"""# **RNN + Attention**"""

class CharRNNAttention(nn.Module):

    def __init__(self, vocab_size, hidden_size):
        super(CharRNNAttention, self).__init__()

        self.hidden_size = hidden_size

        self.embedding = nn.Embedding(vocab_size, hidden_size)
        self.rnn = nn.RNN(hidden_size, hidden_size, batch_first=True)

        # Attention scoring layer
        self.attn = nn.Linear(hidden_size, hidden_size)

        self.fc = nn.Linear(hidden_size, vocab_size)

    def forward(self, x, hidden):

        x = self.embedding(x)
        out, hidden = self.rnn(x, hidden)

        # Attention scores
        attn_weights = torch.softmax(self.attn(out), dim=1)

        # Apply attention
        context = attn_weights * out

        # Predict for ALL time steps
        output = self.fc(context)

        return output, hidden

    def init_hidden(self, batch_size):
        return torch.zeros(1, batch_size, self.hidden_size)

hidden_size = 128

attn_model = CharRNNAttention(vocab_size, hidden_size)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(attn_model.parameters(), lr=0.003)

epochs = 10   # increase training

for epoch in range(epochs):
    total_loss = 0

    for name in encoded_names:

        input_seq = torch.tensor(name[:-1]).unsqueeze(0)
        target_seq = torch.tensor(name[1:]).unsqueeze(0)

        hidden = attn_model.init_hidden(1)

        optimizer.zero_grad()

        output, hidden = attn_model(input_seq, hidden)

        # Compute loss for entire sequence
        loss = criterion(output.squeeze(), target_seq.squeeze())

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

def generate_name_attention(model, start_char, length=10, temperature=0.8):

    model.eval()

    input_seq = torch.tensor([[char_to_idx[start_char]]])
    hidden = model.init_hidden(1)

    name = start_char

    for _ in range(length):

        output, hidden = model(input_seq, hidden)

        # Take last time step output
        logits = output[0, -1] / temperature

        # Convert to probabilities (correct shape)
        probs = torch.softmax(logits, dim=0).detach().numpy()

        # Sample next character
        idx = random.choices(range(vocab_size), weights=probs)[0]

        char = idx_to_char[idx]
        name += char

        input_seq = torch.tensor([[idx]])

    return name

# Generate names
for _ in range(5):
    print(generate_name_attention(attn_model, random.choice(chars)))

# In this step, we generate a large number of names from each model.
# This is necessary because evaluation metrics (novelty and diversity)
# require a sufficiently large sample size to be meaningful.

def generate_multiple(gen_func, model, n=500):
    generated_names = []

    for _ in range(n):
        # Start generation from a random character
        start_char = random.choice(chars)

        # Generate a name using the given model
        name = gen_func(model, start_char)

        # Clean the output (remove spaces/newlines and normalize case)
        name = name.strip().lower()

        generated_names.append(name)

    return generated_names

# Generate names from all three models
rnn_names = generate_multiple(generate_name, model, 500)
blstm_names = generate_multiple(generate_name_blstm, blstm_model, 500)
attn_names = generate_multiple(generate_name_attention, attn_model, 500)

# Print a few samples to quickly inspect outputs
print("RNN Sample:", rnn_names[:5])
print("BLSTM Sample:", blstm_names[:5])
print("Attention Sample:", attn_names[:5])

print("RNN Samples:")
for _ in range(10):
    print(generate_name(model, random.choice(chars)))

print("\nBLSTM Samples:")
for _ in range(10):
    print(generate_name_blstm(blstm_model, random.choice(chars)))

print("\nAttention Samples:")
for _ in range(10):
    print(generate_name_attention(attn_model, random.choice(chars)))

with open("rnn_samples.txt", "w") as f:
    for _ in range(100):
        f.write(generate_name(model, random.choice(chars)) + "\n")

with open("blstm_samples.txt", "w") as f:
    for _ in range(100):
        f.write(generate_name_blstm(blstm_model, random.choice(chars)) + "\n")

with open("attention_samples.txt", "w") as f:
    for _ in range(100):
        f.write(generate_name_attention(attn_model, random.choice(chars)) + "\n")

# Here we prepare the training set for comparison.
# We convert it into a set for faster lookup when computing novelty.

training_names = [name.strip().lower() for name in names]
training_set = set(training_names)

print("Total training names:", len(training_set))

# Novelty Rate measures how many generated names are completely new,
# i.e., not present in the training dataset.

def novelty_rate(generated, training_set):

    new_names = 0

    for name in generated:
        if name not in training_set:
            new_names += 1

    # Return percentage of new (unseen) names
    return (new_names / len(generated)) * 100

# Diversity measures how varied the generated names are.
# It is simply the ratio of unique names to total generated names.

def diversity(generated):

    unique_names = set(generated)

    return len(unique_names) / len(generated)

# RNN
rnn_novelty = novelty_rate(rnn_names, training_set)
rnn_div = diversity(rnn_names)

# BLSTM
blstm_novelty = novelty_rate(blstm_names, training_set)
blstm_div = diversity(blstm_names)

# RNN + Attention
attn_novelty = novelty_rate(attn_names, training_set)
attn_div = diversity(attn_names)


print("RNN -> Novelty:", rnn_novelty, " | Diversity:", rnn_div)
print("BLSTM -> Novelty:", blstm_novelty, " | Diversity:", blstm_div)
print("Attention -> Novelty:", attn_novelty, " | Diversity:", attn_div)

import pandas as pd

results = pd.DataFrame({
    "Model": ["RNN", "BLSTM", "Attention"],
    "Novelty Rate (%)": [rnn_novelty, blstm_novelty, attn_novelty],
    "Diversity": [rnn_div, blstm_div, attn_div]
})

print(results)

import pandas as pd

results = pd.DataFrame({
    "Model": ["RNN", "BLSTM", "Attention"],
    "Novelty Rate (%)": [rnn_novelty, blstm_novelty, attn_novelty],
    "Diversity": [rnn_div, blstm_div, attn_div]
})

results.to_csv("evaluation_results.csv", index=False)

"""# Task -3"""

# For qualitative analysis, we display a few generated samples
# from each model to visually inspect realism and patterns.

print("RNN Samples:")
for _ in range(5):
    print(generate_name(model, random.choice(chars)))

print("\nBLSTM Samples:")
for _ in range(5):
    print(generate_name_blstm(blstm_model, random.choice(chars)))

print("\nAttention Samples:")
for _ in range(5):
    print(generate_name_attention(attn_model, random.choice(chars)))

"""## Task-3: Qualitative Analysis

### * Realism of Generated Names

The three models show noticeable differences in the quality and realism of generated names.

- The **RNN model** produces partially realistic names such as *“Reyansh Sha”* and *“Gupta Chatt”*, which resemble real Indian names. However, some outputs like *“erandeyaner”* and *“deyansh Pan”* appear slightly distorted or incomplete. This indicates that while the RNN captures basic naming patterns, it struggles with consistency.

- The **BLSTM model** generates more structured and consistent patterns such as *“Boniran”*, *“poniran”*, and *“biranir”*. These names follow common phonetic patterns seen in Indian names (e.g., “nir”, “vir”, “ran”). Although not all outputs are real names, they appear more coherent compared to RNN.

- The **Attention-based model** produces outputs like *“hasha haar”*, *“raia eaaria”*, and *“warta haari”*. While these contain recognizable fragments of names, they often include spacing issues and less natural word formations. However, the model shows higher variability and creativity.

---

### * Common Failure Modes

Each model exhibits different types of errors:

- **RNN**:
  - Generates incomplete or truncated names  
  - Occasionally mixes valid name fragments incorrectly  
  - Limited diversity in structure  

- **BLSTM**:
  - Initially produced repetitive patterns (e.g., “rarara”, “nanana”) due to bidirectional training mismatch  
  - After applying constraints, repetition reduced but names still remain synthetic  
  - Tends to repeat learned suffix patterns like “nir” and “vir”  

- **Attention Model**:
  - Produces irregular spacing within names  
  - Generates highly varied but sometimes less realistic outputs  
  - Occasionally forms names that resemble multiple words combined incorrectly  

---

### * Overall Observation

Overall, the models demonstrate a trade-off between realism and diversity:

- The **RNN model** generates more recognizable names but lacks diversity  
- The **BLSTM model** improves structural consistency but still produces artificial patterns  
- The **Attention-based model** achieves the highest diversity but sometimes sacrifices realism  

Thus, the attention-based model performs best in generating varied outputs, while the RNN produces more familiar name structures.
"""